### PR TITLE
:fire: :ambulance: :art: :lock: for a better botstion

### PR DESCRIPTION
**Pull request by SunburntRock89**
haha fuck you

### CODE REVIEW

**Comment by SunburntRock89** [comment]
:fire: :ambulance: :art: :lock: for a better botstion

**Comment by SunburntRock89** [comment]
t

**Comment by SunburntRock89** [comment]
h

**Comment by SunburntRock89** [comment]
e

**Comment by SunburntRock89** [comment]
L

**Comment by theLMGN** [comment]
d

**Comment by theLMGN** [comment]
sad

**Pull request closed without merging**
